#!/usr/bin/env node
/*
 * Repo CI check. Run it from the repo root:  node scripts/lint.mjs
 *
 * Checks
 *   skills     every skills/<dir>/SKILL.md has name == <dir> and a non-empty
 *              description of at most 1024 characters
 *   agents     every agents/<name>.md has name == <name>, a description and a model
 *   manifest   every skill/agent it names exists, and every skill/agent on disk
 *              belongs to some bundle
 *   harnesses  harnesses.json parses and every entry declares `skills`
 *   forbidden  a case-insensitive scan for private strings across text files,
 *              with scripts/lint-allow.txt as the escape hatch
 *   syntax     node --check bin/install.mjs
 *
 * Exits 1 and lists everything that is wrong.
 */

import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { parseFrontmatter } from '../bin/install.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MAX_DESCRIPTION = 1024;

const FORBIDDEN = ['genea', 'getgenea', '/Users/vimoxshah', 'cerebri', 'gdk'];
const TEXT_EXTENSIONS = new Set(['.md', '.mjs', '.js', '.json', '.sh', '.yml', '.yaml', '.txt', '.toml']);
const SKIP_DIRS = new Set(['.git', 'node_modules', '.DS_Store']);
const SKIP_PATHS = new Set([
  // These two hold the forbidden strings on purpose: the list above, and the
  // allowlist that pardons the deliberate mentions.
  'scripts/lint.mjs',
  'scripts/lint-allow.txt',
  // Generated by the installer when the repo itself is the central dir.
  '.installed.json',
]);
const SKIP_PREFIXES = ['skills/design-kit/fonts/cache/'];

const failures = [];
const fail = (group, message) => failures.push({ group, message });

const rel = (p) => path.relative(ROOT, p).split(path.sep).join('/');
const read = (p) => fs.readFileSync(p, 'utf8');
const exists = (p) => {
  try { fs.lstatSync(p); return true; } catch { return false; }
};
const dirsIn = (p) => (exists(p) ? fs.readdirSync(p, { withFileTypes: true }).filter((e) => e.isDirectory()).map((e) => e.name).sort() : []);
const filesIn = (p, ext) => (exists(p) ? fs.readdirSync(p, { withFileTypes: true }).filter((e) => e.isFile() && e.name.endsWith(ext)).map((e) => e.name).sort() : []);

/* ------------------------------------------------------------------ skills */

const skillNames = dirsIn(path.join(ROOT, 'skills'));
for (const dir of skillNames) {
  const file = path.join(ROOT, 'skills', dir, 'SKILL.md');
  if (!exists(file)) { fail('skills', `skills/${dir}/SKILL.md is missing`); continue; }
  const { data } = parseFrontmatter(read(file));
  if (!Object.keys(data).length) { fail('skills', `skills/${dir}/SKILL.md has no frontmatter`); continue; }
  if (data.name !== dir) fail('skills', `skills/${dir}/SKILL.md declares name "${data.name ?? ''}", expected "${dir}"`);
  const description = String(data.description || '').trim();
  if (!description) fail('skills', `skills/${dir}/SKILL.md has an empty description`);
  else if (description.length > MAX_DESCRIPTION) fail('skills', `skills/${dir}/SKILL.md description is ${description.length} characters, the limit is ${MAX_DESCRIPTION}`);
}

/* ------------------------------------------------------------------ agents */

const agentFiles = filesIn(path.join(ROOT, 'agents'), '.md');
const agentNames = agentFiles.map((f) => path.basename(f, '.md'));
for (const file of agentFiles) {
  const stem = path.basename(file, '.md');
  const { data } = parseFrontmatter(read(path.join(ROOT, 'agents', file)));
  if (!Object.keys(data).length) { fail('agents', `agents/${file} has no frontmatter`); continue; }
  if (data.name !== stem) fail('agents', `agents/${file} declares name "${data.name ?? ''}", expected "${stem}"`);
  if (!String(data.description || '').trim()) fail('agents', `agents/${file} has an empty description`);
  if (!String(data.model || '').trim()) fail('agents', `agents/${file} has no model`);
}

/* ---------------------------------------------------------------- manifest */

let manifest = null;
try {
  manifest = JSON.parse(read(path.join(ROOT, 'manifest.json')));
} catch (err) {
  fail('manifest', `manifest.json does not parse: ${err.message}`);
}

if (manifest) {
  const claimedSkills = new Set();
  const claimedAgents = new Set();
  for (const [id, bundle] of Object.entries(manifest.bundles || {})) {
    for (const skill of bundle.skills || []) {
      claimedSkills.add(skill);
      if (!skillNames.includes(skill)) fail('manifest', `bundle "${id}" names skill "${skill}", which is not in skills/`);
    }
    for (const agent of bundle.agents || []) {
      claimedAgents.add(agent);
      if (!agentNames.includes(agent)) fail('manifest', `bundle "${id}" names agent "${agent}", which is not in agents/`);
    }
    for (const [key, dir] of [['commands', 'commands'], ['outputStyles', 'output-styles'], ['routing', 'routing']]) {
      for (const file of bundle[key] || []) {
        if (!exists(path.join(ROOT, dir, file))) fail('manifest', `bundle "${id}" names ${dir}/${file}, which does not exist`);
      }
    }
    if (bundle.statusline && !exists(path.join(ROOT, 'statusline', bundle.statusline))) {
      fail('manifest', `bundle "${id}" names statusline/${bundle.statusline}, which does not exist`);
    }
  }
  for (const skill of skillNames) {
    if (!claimedSkills.has(skill)) fail('manifest', `skills/${skill} is in no bundle`);
  }
  for (const agent of agentNames) {
    if (!claimedAgents.has(agent)) fail('manifest', `agents/${agent}.md is in no bundle`);
  }
  for (const id of manifest.default || []) {
    if (!manifest.bundles?.[id]) fail('manifest', `default names bundle "${id}", which is not defined`);
  }
  if (!manifest.centralDir) fail('manifest', 'manifest.json has no centralDir');
}

/* --------------------------------------------------------------- harnesses */

try {
  const harnesses = JSON.parse(read(path.join(ROOT, 'harnesses.json')));
  if (!harnesses.universal?.skills) fail('harnesses', 'harnesses.json has no universal.skills');
  for (const [id, harness] of Object.entries(harnesses.harnesses || {})) {
    if (!harness.skills) fail('harnesses', `harness "${id}" has no skills path`);
    if (harness.agents && !harness.agents.dir) fail('harnesses', `harness "${id}" has agents but no agents.dir`);
  }
} catch (err) {
  fail('harnesses', `harnesses.json does not parse: ${err.message}`);
}

/* --------------------------------------------------------------- forbidden */

function loadAllowlist() {
  const file = path.join(ROOT, 'scripts', 'lint-allow.txt');
  if (!exists(file)) return [];
  return read(file)
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#'))
    .map((line) => {
      const cut = line.indexOf(':');
      if (cut === -1) return null;
      return { path: line.slice(0, cut).trim(), needle: line.slice(cut + 1).trim().toLowerCase() };
    })
    .filter(Boolean);
}

function walk(dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (SKIP_DIRS.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (entry.isFile() && TEXT_EXTENSIONS.has(path.extname(entry.name))) out.push(full);
  }
  return out;
}

const allowlist = loadAllowlist();
for (const file of walk(ROOT)) {
  const relative = rel(file);
  if (SKIP_PATHS.has(relative) || SKIP_PREFIXES.some((p) => relative.startsWith(p))) continue;
  const lines = read(file).split('\n');
  lines.forEach((line, index) => {
    const lower = line.toLowerCase();
    for (const term of FORBIDDEN) {
      if (!lower.includes(term.toLowerCase())) continue;
      const pardoned = allowlist.some((rule) => rule.path === relative && lower.includes(rule.needle) && rule.needle.includes(term.toLowerCase()));
      if (pardoned) continue;
      const snippet = line.trim().slice(0, 100);
      fail('forbidden', `${relative}:${index + 1} contains "${term}"  ${snippet}`);
    }
  });
}

/* ------------------------------------------------------------------ syntax */

const check = spawnSync(process.execPath, ['--check', path.join(ROOT, 'bin', 'install.mjs')], { encoding: 'utf8' });
if (check.status !== 0) fail('syntax', `bin/install.mjs does not parse:\n${(check.stderr || '').trim()}`);

/* ------------------------------------------------------------------ report */

const groups = ['skills', 'agents', 'manifest', 'harnesses', 'forbidden', 'syntax'];
for (const group of groups) {
  const found = failures.filter((f) => f.group === group);
  if (!found.length) {
    console.log(`ok    ${group}`);
    continue;
  }
  console.log(`FAIL  ${group}  (${found.length})`);
  for (const item of found) console.log(`  - ${item.message}`);
}

if (failures.length) {
  console.log(`\n${failures.length} problem${failures.length === 1 ? '' : 's'}. Deliberate mentions go in scripts/lint-allow.txt as "path:substring".`);
  process.exit(1);
}
console.log('\nall clean');
